# Run linters automatically on pull requests.
name: Lint rosbag2
on:
  pull_request:

jobs:
  ament_lint_general: # tests applicable to all packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [copyright, xmllint]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: ${{ matrix.linter }}
        distribution: rolling
        package-name: |
            ros2bag
            rosbag2
            rosbag2_compression
            rosbag2_compression_zstd
            rosbag2_cpp
            rosbag2_interfaces
            rosbag2_py
            rosbag2_storage
            rosbag2_storage_default_plugins
            rosbag2_test_common
            rosbag2_tests
            rosbag2_transport
            shared_queues_vendor

  ament_lint_cpp: # Linters applicable to C++ packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [cppcheck, cpplint, uncrustify]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: ${{ matrix.linter }}
        distribution: rolling
        package-name: |
            rosbag2_compression
            rosbag2_compression_zstd
            rosbag2_cpp
            rosbag2_py
            rosbag2_storage
            rosbag2_storage_default_plugins
            rosbag2_test_common
            rosbag2_tests
            rosbag2_transport
            shared_queues_vendor

  clang_tidy_cpp: # Runs Clang-Tidy on cpp files
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
        linter: [clang-tidy]
    steps:
    - uses: ros-tooling/action-ros-ci@v0.2
      with:
        package-name: |
          ros2bag
          rosbag2
          rosbag2_compression
          rosbag2_compression_zstd
          rosbag2_cpp
          rosbag2_interfaces
          rosbag2_py
          rosbag2_storage
          rosbag2_storage_default_plugins
          rosbag2_test_common
          rosbag2_tests
          rosbag2_transport
          shared_queues_vendor
          sqlite3_vendor
          zstd_vendor
        target-ros2-distro: rolling
        vcs-repo-file-url: https://raw.githubusercontent.com/ros2/ros2/master/ros2.repos
        colcon-defaults: |
          {
            "build": {
              "cmake-args": [
                "-DCMAKE_CXX_FLAGS=\"-Werror\"",
                "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON"
              ]
            }
          }
    - uses: ros-tooling/checkout@v2
      with:
        linter: ${{ matrix.linter }}
        package-name: libstatistics_collector

  ament_lint_python: # Linters applicable to Python packages
    name: ament_${{ matrix.linter }}
    runs-on: ubuntu-latest
    container:
      image: rostooling/setup-ros-docker:ubuntu-focal-ros-rolling-ros-base-latest
    strategy:
      fail-fast: false
      matrix:
          linter: [pep257, flake8]
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/action-ros-lint@v0.1
      with:
        linter: ${{ matrix.linter }}
        distribution: rolling
        package-name: |
            ros2bag
            rosbag2_py
